version: "3"
services:
    lab-items:
        build: .
        ports:
            - 8080:8080
        environment:
            DB_HOST: jdbc:h2:mem:lab_db
            DB_USER: sa
            DB_PASSWORD: password
        volumes:
            - db_data:/var/lib/h2
volumes:
    db_data: {}