version: "3"
services:
    lab-items:
        depends_on:
          - mysql
        build: .
        ports:
            - 8080:8080
        environment:
            DB_HOST: mysql:3306
            DB_USER: lab_user
            DB_PASSWORD: lab_pass
            DB_NAME: lab_db
    mysql:
        image: mysql:8
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: lab_db
            MYSQL_USER: lab_user
            MYSQL_PASSWORD: lab_pass
            MYSQL_ROOT_PASSWORD: lab_rootpass
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data: {}